apiVersion: v1
kind: Secret
metadata:
  name: b2b-client-api-secrets
type: Opaque
data:
  RedisUrl: {{ .Values.redisUrl | b64enc | quote }}
  ConnectionString: {{ .Values.clientApi.connectionString | b64enc | quote }}
  LogzIoToken: {{ .Values.logzIoToken | b64enc | quote }}
  SendGridApiKey: {{ .Values.sendGridApiKey | b64enc | quote }}