trigger: none

pr: none

resources:
  pipelines:
  - pipeline: AnalyticsApiBuild
    source: '[Analytics Api] Build'
    trigger: 
      branches:
        include: 
        - main

variables:
- group: global
- template: './variables.yml'
- name: k8sReleaseName
  value: 'b2b-analytics-api'
- name: helmVersionToInstall
  value: '3.3.4'
- name: helmChartPath
  value: '$(Pipeline.Workspace)/helm-chart'

stages:
- stage: Production
  variables:
  - group: production
  - group: b2b-analytics-api-production
  jobs:
  - deployment:
    pool:
      vmImage: 'ubuntu-latest'
    environment: Production
    strategy:
      runOnce:
        deploy:
          steps:
          - task: ExtractFiles@1
            displayName: Extract Helm Chart
            inputs:
              archiveFilePatterns: '$(Pipeline.Workspace)/AnalyticsApiBuild/drop/helm-chart.zip'
              destinationFolder: $(helmChartPath)
          - task: HelmInstaller@1
            displayName: Install Helm
            inputs:
              helmVersionToInstall: $(helmVersionToInstall)
          - task: HelmDeploy@0
            displayName: Login to Kubernetes
            inputs:
              command: login
              azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
              azureResourceGroup: $(azureResourceGroup)
              kubernetesCluster: $(kubernetesCluster)
          - script: |
              stringConnectionString="$(connectionString)"
              escapedConnectionString=${stringConnectionString//,/\\,}

              helm upgrade --install --wait \
              --set image.registry='$(acrLoginServer)' \
              --set image.repository='$(b2bAnalyticsApiImageRepository)' \
              --set image.tag='$(Resources.Pipeline.AnalyticsApiBuild.RunID)' \
              --set environment='$(environment)' \
              --set identityUrl='$(identityUrl)' \
              --set clientUrl='$(clientUrl)' \
              --set catalogUrl='$(catalogUrl)' \
              --set globalUrl='$(globalUrl)' \
              --set tokenUrl='$(tokenUrl)' \
              --set giuruApiOrganisationId='$(giuruApiOrganisationId)' \
              --set giuruApiEmail='$(giuruApiEmail)' \
              --set giuruApiSecret='$(giuruApiSecret)' \
              --set redisUrl='$(redisUrl)' \
              --set logzIoToken='$(logzIoToken)' \
              --set logzIoType='$(logzIoType)' \
              --set logzIoDataCenterSubDomain='$(logzIoDataCenterSubDomain)' \
              --set eventBusConnection='$(eventBusConnection)' \
              --set eventBusRetryCount=`$(eventBusRetryCount)` \
              --set eventBusRequestedHeartbeat=`$(eventBusRequestedHeartbeat)` \
              --set openTelemetryCollectorUrl='$(openTelemetryCollectorUrl)' \
              --set analyticsApi.connectionString="$escapedConnectionString" \
              --set ingress.analyticsapidomain='$(analyticsApiDomain)' \
              $(k8sReleaseName) $(helmChartPath)
            displayName: Deploy to Kubernetes