trigger: none

pr: none

resources:
  pipelines:
  - pipeline: NewsApiBuild
    source: '[News Api] Build'
    trigger: 
      branches:
        include: 
        - main

variables:
- group: eltap
- template: '../variables.yml'
- name: k8sReleaseName
  value: 'b2b-news-api'
- name: helmVersionToInstall
  value: '3.3.4'
- name: helmChartPath
  value: '$(Pipeline.Workspace)/helm-chart'

stages:
- stage: Production
  variables:
  - group: eltap-production
  - group: eltap-b2b-news-api-production
  jobs:
  - deployment:
    pool:
      vmImage: 'ubuntu-latest'
    environment: Production
    strategy:
      runOnce:
        deploy:
          steps:
          - task: ExtractFiles@1
            displayName: Extract Helm Chart
            inputs:
              archiveFilePatterns: '$(Pipeline.Workspace)/NewsApiBuild/drop/helm-chart.zip'
              destinationFolder: $(helmChartPath)
          - task: HelmInstaller@1
            displayName: Install Helm
            inputs:
              helmVersionToInstall: $(helmVersionToInstall)
          - task: HelmDeploy@0
            displayName: Login to Kubernetes
            inputs:
              command: login
              azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
              azureResourceGroup: $(azureResourceGroup)
              kubernetesCluster: $(kubernetesCluster)
          - script: |
              stringConnectionString="$(connectionString)"
              escapedConnectionString=${stringConnectionString//,/\\,}

              helm upgrade --install --wait \
              --set image.registry='$(acrLoginServer)' \
              --set image.repository='$(b2bNewsApiImageRepository)' \
              --set image.tag='$(Resources.Pipeline.NewsApiBuild.RunID)' \
              --set environment='$(environment)' \
              --set identityUrl='$(identityUrl)' \
              --set redisUrl='$(redisUrl)' \
              --set logzIoToken='$(logzIoToken)' \
              --set logzIoType='$(logzIoType)' \
              --set logzIoDataCenterSubDomain='$(logzIoDataCenterSubDomain)' \
              --set openTelemetryCollectorUrl='$(openTelemetryCollectorUrl)' \
              --set newsApi.connectionString="$escapedConnectionString" \
              --set ingress.newsapidomain='$(newsApiDomain)' \
              $(k8sReleaseName) $(helmChartPath)
            displayName: Deploy to Kubernetes