trigger: none

pr: none

resources:
  pipelines:
  - pipeline: SellerWebBuild
    source: '[Seller Web] Build'
    trigger: 
      branches:
        include: 
        - main

variables:
- group: global
- template: './variables.yml'
- name: k8sReleaseName
  value: 'b2b-seller-web'
- name: helmVersionToInstall
  value: '3.3.4'
- name: helmChartPath
  value: '$(Pipeline.Workspace)/helm-chart'

stages:
- stage: Production
  variables:
  - group: production
  - group: b2b-seller-web-production
  jobs:
  - deployment:
    pool:
      vmImage: 'ubuntu-latest'
    environment: Production
    strategy:
      runOnce:
        deploy:
          steps:
          - task: ExtractFiles@1
            displayName: Extract Helm Chart
            inputs:
              archiveFilePatterns: '$(Pipeline.Workspace)/SellerWebBuild/drop/helm-chart.zip'
              destinationFolder: $(helmChartPath)
          - task: HelmInstaller@1
            displayName: Install Helm
            inputs:
              helmVersionToInstall: $(helmVersionToInstall)
          - task: HelmDeploy@0
            displayName: Login to Kubernetes
            inputs:
              command: login
              azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
              azureResourceGroup: $(azureResourceGroup)
              kubernetesCluster: $(kubernetesCluster)
          - script: |
              helm upgrade --install --wait \
              --set image.registry='$(acrLoginServer)' \
              --set image.sellerWeb.repository='$(b2bSellerWebImageRepository)' \
              --set image.sellerWebReactSsr.repository='$(b2bSellerWebReactSsrImageRepository)' \
              --set image.tag='$(Resources.Pipeline.SellerWebBuild.RunID)' \
              --set environment='$(environment)' \
              --set nodeEnvironment='$(nodeEnvironment)' \
              --set serverSideRenderingEndpoint='$(serverSideRenderingEndpoint)' \
              --set catalogUrl='$(catalogUrl)' \
              --set analyticsUrl='$(catalogUrl)' \
              --set mediaUrl='$(mediaUrl)' \
              --set identityUrl='$(identityUrl)' \
              --set redisUrl='$(redisUrl)' \
              --set inventoryUrl='$(inventoryUrl)' \
              --set clientUrl='$(clientUrl)' \
              --set basketUrl='$(basketUrl)' \
              --set orderUrl='$(orderUrl)' \
              --set newsUrl='$(newsUrl)' \
              --set downloadCenterUrl='$(downloadCenterUrl)' \
              --set cdnUrl='$(cdnUrl)' \
              --set sellerUrl='$(sellerUrl)' \
              --set buyerUrl='$(buyerUrl)' \
              --set globalUrl='$(globalUrl)' \
              --set contentUrl='$(contentAdminUrl)' \
              --set logzIoToken='$(logzIoToken)' \
              --set logzIoType='$(logzIoType)' \
              --set logzIoDataCenterSubDomain='$(logzIoDataCenterSubDomain)' \
              --set openTelemetryTracingCollectorUrl='$(openTelemetryTracingCollectorUrl)' \
              --set sellerWeb.clientId='$(clientId)' \
              --set sellerWeb.clientSecret='$(clientSecret)' \
              --set ingress.sellerwebdomain='$(sellerWebDomain)' \
              $(k8sReleaseName) $(helmChartPath)
            displayName: Deploy to Kubernetes