apiVersion: v1
kind: Secret
metadata:
  name: b2b-buyer-web-secrets
type: Opaque
data:
  RedisUrl: {{ .Values.redisUrl | b64enc | quote }}
  LogzIoToken: {{ .Values.logzIoToken | b64enc | quote }}
  ContentGraphQlAuthorizationKey: {{ .Values.contentGraphQlAuthorizationKey | b64enc | quote }}
  ClientId: {{ .Values.buyerWeb.clientId | b64enc | quote }}
  ClientSecret: {{ .Values.buyerWeb.clientSecret | b64enc | quote }}
  GoogleTagManagerIdentifier: {{ .Values.buyerWeb.googleTagManagerIdentifier | b64enc | quote }}