apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordering-api-deployment
  labels:
    app: ordering-api
spec:
  replicas: {{ .Values.orderingApi.replicas }}
  selector:
    matchLabels:
      app: ordering-api
  template:
    metadata:
      labels:
        app: ordering-api
    spec:
      containers:
      - name: ordering-api-container
        image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        readinessProbe:
          httpGet:
            path: /hc
            port: 80
          initialDelaySeconds: {{ .Values.orderingApi.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.orderingApi.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.orderingApi.readinessProbe.timeoutSeconds }}
        livenessProbe:
          httpGet:
            path: /liveness
            port: 80
          initialDelaySeconds: {{ .Values.orderingApi.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.orderingApi.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.orderingApi.livenessProbe.timeoutSeconds }}
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: {{ .Values.environment }}
        - name: IdentityUrl
          value: {{ .Values.identityUrl }}
        - name: MediaUrl
          value: {{ .Values.mediaUrl }}
        - name: LogzIoType
          value: {{ .Values.logzIoType }}
        - name: LogzIoDataCenterSubDomain
          value: {{ .Values.logzIoDataCenterSubDomain }}
        - name: OpenTelemetryCollectorUrl
          value: {{ .Values.openTelemetryCollectorUrl }}
        - name: EventBusRetryCount
          value: {{ .Values.eventBusRetryCount }}
        - name: EventBusRequestedHeartbeat
          value: {{ .Values.eventBusRequestedHeartbeat }}
        - name: SenderName
          value: {{ .Values.senderName }}
        - name: SenderEmail
          value: {{ .Values.senderEmail }}
        - name: ApplyRecipientEmail
          value: {{ .Values.applyRecipientEmail }}
        - name: ActionSendGridCustomOrderTemplateId
          value: {{ .Values.orderingApi.actionSendGridCustomOrderTemplateId }}
        - name: DefaultCulture
          value: {{ .Values.defaultCulture }}
        - name: SupportedCultures
          value: {{ .Values.supportedCultures }}
        envFrom:
        - secretRef:
            name: b2b-ordering-api-secrets
        ports:
        - containerPort: 80