apiVersion: v1
kind: Secret
metadata:
  name: b2b-ordering-api-secrets
type: Opaque
data:
  RedisUrl: {{ .Values.redisUrl | b64enc | quote }}
  ConnectionString: {{ .Values.orderingApi.connectionString | b64enc | quote }}
  LogzIoToken: {{ .Values.logzIoToken | b64enc | quote }}
  SendGridApiKey: {{ .Values.sendGridApiKey | b64enc | quote }}