FROM node:18.0-alpine

RUN apk update && apk add python3 make g++

RUN mkdir -p /home/node/aspnetcore-react-ssr/node_modules && chown -R node:node /home/node/aspnetcore-react-ssr

WORKDIR /home/node/aspnetcore-react-ssr

COPY package*.json ./

USER node

RUN npm install --legacy-peer-deps

COPY --chown=node:node . .

ENV NODE_ENV=development

EXPOSE 3000

CMD ["node", "server/bootstrap.js" ]