#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/sdk:3.1.302 AS build-env
WORKDIR /app

COPY ./src/Infrastructure ./Infrastructure/
COPY ./src/Feature ./Feature/
COPY ./src/Project/Api ./Project/Api/
RUN dotnet publish ./Project/Api/Api.csproj -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1.6
WORKDIR /app
COPY --from=build-env /app/out .

ENTRYPOINT ["dotnet", "Api.dll"]