version: '3.9'

services:

  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"

  azurite:
    ports:
      - "10000:10000"
      - "10001:10001"
    volumes:
      - azuritedata:/data

  elasticsearch:
    volumes:
      - elasticsearchdata:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    environment:
      - ELASTICSEARCH_HOSTS=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:9200
    ports:
      - 5601:5601

  logstash:
    volumes:
      - ./DockerServices/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./DockerServices/logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "31311:31311"

  react-ssr:
    environment: 
      NODE_ENV: development

  sqldata:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Gre@tPassw0rd
    ports:
      - "5433:1433"
    volumes:
      - mssqldata:/var/opt/mssql

  media-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sqldata;Database=MediaDb;User Id=sa;Password=Gre@tPassw0rd
      - StorageConnectionString=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;
      - IdentityUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5105
      - LogstashUrl=http://logstash:31311
      - SupportedCultures=${SUPPORTED_CULTURES}
      - DefaultCulture=${DEFAULT_CULTURE}
      - OrganisationId=${ORGANISATION_ID}
      - EventBusConnection=amqp://rabbitmq
      - EventBusRetryCount=5
      - EventBusRequestedHeartbeat=60
    ports:
      - "5131:80"

  client-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sqldata;Database=ClientDb;User Id=sa;Password=Gre@tPassw0rd
      - IdentityUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5105
      - LogstashUrl=http://logstash:31311
      - SupportedCultures=${SUPPORTED_CULTURES}
      - DefaultCulture=${DEFAULT_CULTURE}
      - SenderEmail=${SENDER_EMAIL}
      - SenderName=${SENDER_NAME}
      - SendGridApiKey=${SENDGRID_API_KEY}
      - ActionSendGridClientApplyConfirmationTemplateId=${SENDGRID_CLIENT_APPLY_CONFIRMATION_TEMPLATE_ID}
      - ActionSendGridClientApplyTemplateId=${SENDGRID_CLIENT_APPLY_TEMPLATE_ID}
    ports:
      - "5133:80"

  inventory-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sqldata;Database=InventoryDb;User Id=sa;Password=Gre@tPassw0rd
      - IdentityUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5105
      - LogstashUrl=http://logstash:31311
      - SupportedCultures=${SUPPORTED_CULTURES}
      - DefaultCulture=${DEFAULT_CULTURE}
      - EventBusConnection=amqp://rabbitmq
      - EventBusRetryCount=5
      - EventBusRequestedHeartbeat=60
    ports:
      - "5134:80"

  news-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sqldata;Database=NewsDb;User Id=sa;Password=Gre@tPassw0rd
      - IdentityUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5105
      - LogstashUrl=http://logstash:31311
      - SupportedCultures=${SUPPORTED_CULTURES}
      - DefaultCulture=${DEFAULT_CULTURE}
    ports:
      - "5135:80"

  catalog-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sqldata;Database=CatalogDb;User Id=sa;Password=Gre@tPassw0rd
      - MediaUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5131
      - IdentityUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5105
      - EventBusConnection=amqp://rabbitmq
      - EventBusRetryCount=5
      - EventBusRequestedHeartbeat=60
      - ElasticsearchUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:9200
      - LogstashUrl=http://logstash:31311
      - ElasticsearchIndex=catalog
      - Brands=4a8f8442-43b0-4223-83bb-978d5e81acc7&ELTAP&09affcc9-1665-45d6-919f-3d2026106ba1
      - SupportedCultures=${SUPPORTED_CULTURES}
      - DefaultCulture=${DEFAULT_CULTURE}
    ports:
      - "5101:80"

  catalog-backgroundtasks:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sqldata;Database=CatalogDb;User Id=sa;Password=Gre@tPassw0rd
      - MediaUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5131
      - IdentityUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5105
      - EventBusConnection=amqp://rabbitmq
      - EventBusRetryCount=5
      - EventBusRequestedHeartbeat=60
      - ElasticsearchUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:9200
      - LogstashUrl=http://logstash:31311
      - ElasticsearchIndex=catalog
      - SupportedCultures=${SUPPORTED_CULTURES}
      - DefaultCulture=${DEFAULT_CULTURE}
    ports:
      - "5132:80"

  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ServerSideRenderingEndpoint=http://react-ssr:3000
      - CatalogUrl=http://catalog-api
      - MediaUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5131
      - IdentityUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5105
      - LogstashUrl=http://logstash:31311
      - ConnectionString=Server=sqldata;Database=IdentityDb;User Id=sa;Password=Gre@tPassw0rd
      - Clients=663bba90-0036-4a58-8516-39faa8baba87&c61fcb32-cf9b-4cdd-84dc-4a1b173c36e9&${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5104;d9316849-7e98-4c5b-853b-5a322aecdc75&693667b0-545e-48b6-9ef8-02ada81be946&${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5107
      - SellerClientId=663bba90-0036-4a58-8516-39faa8baba87
      - Accounts=seller@user.com&Greg&Salesman&Gre@tPassw0rd&09affcc9-1665-45d6-919f-3d2026106ba1
      - Organisations=${ORGANISATION_ID}&ELTAP&eltap&eltap.com&True&EN&98daf0da-89ac-48db-8b9f-edc6383153ed&biuro@eltap.com&Fabryka%20mebli%20tapicerowanych%20ELTAP%20powsta%C5%82a%20w%201993%20roku.%20Jej%20za%C5%82o%C5%BCycielem%20jest%20Leszek%20Dworak%2C%20kt%C3%B3ry%20wraz%20w%20ma%C5%82%C5%BConk%C4%85%20prowadzi%C5%82%20firm%C4%99%20do%202020%20roku%20-%20od%20tego%20czasu%20firma%20zmieni%C5%82a%20status%20prawny%20na%20ELTAP%20Sp%C3%B3%C5%82ka%20z%20ograniczon%C4%85%20odpowiedzialno%C5%9Bci%C4%85%20Sp.k.%20do%20kt%C3%B3rej%20do%C5%82%C4%85czy%C5%82%20syn.%20Firma%20na%20przestrzeni%20lat%2C%20na%20skutek%20rozwoju%2C%20zyska%C5%82a%20miano%20znanej%20i%20cenionej%20marki%20na%20rynku%20polskim%20oraz%20mi%C4%99dzynarodowym.%20Przedsi%C4%99biorstwo%20posiada%2026-letnie%20do%C5%9Bwiadczenie%2C%20kt%C3%B3re%20poparte%20pasj%C4%85%20i%20zami%C5%82owaniem%20do%20meblarstwa%20sprawia%2C%20%C5%BCe%20produkowane%20meble%20zaspokajaj%C4%85%20gusta%20nawet%20najbardziej%20wymagaj%C4%85cych%20Klient%C3%B3w.%20Dzi%C5%9B%20firma%20ELTAP%20to%20przedsi%C4%99biorstwo%2C%20kt%C3%B3re%20specjalizuje%20si%C4%99%20w%20produkcji%20naro%C5%BCnik%C3%B3w%2C%20boxspring%C3%B3w%2C%20sof%2C%20foteli%2C%20%C5%82%C3%B3%C5%BCek%2C%20materacy%2C%20puf%20i%20wielu%20innych%20produkt%C3%B3w.%20Zatrudniamy%20ponad%20180%20pracownik%C3%B3w%2C%20a%20w%20zwi%C4%85zku%20z%20naszym%20rozwojem%20ci%C4%85gle%20poszukujemy%20nowych.%20Jeste%C5%9Bmy%20pr%C4%99%C5%BCnie%20rozwijaj%C4%85c%C4%85%20si%C4%99%20firm%C4%85%20z%20wykwalifikowan%C4%85%20za%C5%82og%C4%85%20specjalist%C3%B3w%2C%20kt%C3%B3ra%20dok%C5%82ada%20wszelkich%20stara%C5%84%2C%20aby%20nasze%20meble%20zapewnia%C5%82y%20komfortowy%20odpoczynek%20i%20zadawala%C5%82y%20gusta%20Klient%C3%B3w%20w%20ca%C5%82ej%20Europie.&The%20ELTAP%20upholstered%20furniture%20factory%20was%20established%20in%201993.%20Its%20founder%20was%20Leszek%20Dworak%2C%20who%20ran%20the%20company%20together%20with%20his%20wife%20until%202020%2C%20when%20the%20company%20changed%20its%20legal%20status%20to%20ELTAP%20Sp.%20z%20o.o.%20Sp.k.%20%28a%20limited%20liability%20partnership%29%20with%20the%20founder%E2%80%99s%20son%20joining%20as%20a%20partner.%20Over%20the%20years%20the%20company%20has%20grown%20into%20a%20well-known%20and%20valued%20brand%20in%20Polish%20and%20international%20markets.%20With%2026%20years%20of%20experience%20in%20the%20industry%2C%20backed%20by%20passion%20and%20a%20love%20for%20furniture%20making%2C%20the%20company%20is%20able%20to%20successfully%20supply%20even%20the%20most%20demanding%20of%20clients.%20Today%2C%20ELTAP%20specialises%20in%20the%20design%20and%20production%20of%20corner%20sofas%2C%20boxspring%20beds%2C%20couches%2C%20chairs%2C%20beds%2C%20mattresses%2C%20pouffes%2C%20and%20many%20other%20types%20of%20furniture.%20We%20have%20more%20than%20180%20employees%20and%20hiring%20more%20as%20we%20grow.%20We%20are%20a%20thriving%20company%20with%20a%20team%20of%20highly%20qualified%20specialists%20who%20make%20every%20effort%20to%20ensure%20that%20our%20furniture%20guarantees%20relaxation%2C%20lounging%20and%20sleeping%20in%20comfort%2C%20to%20the%20best%20satisfaction%20of%20customers%20across%20Europe.&Das%20Polsterm%C3%B6belwerk%20ELTAP%20wurde%201993%20gegr%C3%BCndet.%20Das%20Unternehmen%20wurde%20von%20Leszek%20Dworak%20gegr%C3%BCndet%2C%20der%20das%20Unternehmen%20zusammen%20mit%20seiner%20Frau%20bis%202020%20leitete.%20Zu%20dieser%20Zeit%20wurde%20der%20rechtliche%20Status%20des%20Unternehmens%2C%20dem%20der%20Sohn%20beigetreten%20ist%2C%20in%20ELTAP%20Sp%C3%B3%C5%82ka%20z%20ograniczon%C4%85%20odpowiedzialno%C5%9Bci%C4%85%20Sp.k.%20%5BGesellschaft%20mit%20beschr%C3%A4nkter%20Haftung%20Kommanditgesellschaft%5D%20ge%C3%A4ndert.%20Im%20Laufe%20der%20Jahre%20ist%20das%20Unternehmen%20aufgrund%20seiner%20Entwicklung%20sowohl%20auf%20dem%20polnischen%20Markt%20als%20auch%20international%20zu%20einer%20bekannten%20und%20angesehenen%20Marke%20geworden.%20Das%20Unternehmen%20verf%C3%BCgt%20%C3%BCber%2026%20Jahre%20Erfahrung%2C%20die%20in%20Verbindung%20mit%20Leidenschaft%20und%20Liebe%20zu%20M%C3%B6beln%20dazu%20f%C3%BChrt%2C%20dass%20die%20hergestellten%20M%C3%B6bel%20den%20Geschmack%20selbst%20der%20anspruchsvollsten%20Kunden%20befriedigen.%20Heute%20ist%20ELTAP%20ein%20Unternehmen%2C%20das%20sich%20auf%20die%20Herstellung%20von%20Ecksofas%2C%20Boxspringbetten%2C%20Sofas%2C%20Sesseln%2C%20Betten%2C%20Matratzen%2C%20Polsterhockern%20und%20vielen%20anderen%20Produkten%20spezialisiert.%20Wir%20besch%C3%A4ftigen%20%C3%BCber%20180%20Mitarbeiter%20und%20suchen%20aufgrund%20unserer%20Entwicklung%20st%C3%A4ndig%20nach%20neuen%20Arbeitskr%C3%A4ften.%20Wir%20sind%20ein%20dynamisch%20wachsendes%20Unternehmen%20mit%20einem%20qualifizierten%20Team%20von%20Fachleuten%2C%20das%20alle%20Anstrengungen%20unternimmt%2C%20um%20sicherzustellen%2C%20dass%20unsere%20M%C3%B6bel%20eine%20komfortable%20Erholung%20bieten%20und%20den%20Geschmack%20der%20Kunden%20in%20ganz%20Europa%20befriedigen.
      - SupportedCultures=${SUPPORTED_CULTURES}
      - PrivacyPolicy=Privacy%20Policy
      - Regulations=Regulations
      - BuyerUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5107
      - DefaultCulture=${DEFAULT_CULTURE}
      - ApplyRecipientEmail=office@eltap.com
      - SenderEmail=${SENDER_EMAIL}
      - SenderName=${SENDER_NAME}
      - SendGridApiKey=${SENDGRID_API_KEY}
      - ActionSendGridCreateTemplateId=${SENDGRID_CREATE_ACCOUNT_TEMPLATE_ID}
      - ActionSendGridResetTemplateId=${SENDGRID_RESET_PASSWORD_TEMPLATE_ID}
      - DevelopersEmail=it.developers@eltap.com
    ports:
      - "5105:80"

  basketdata:
    ports:
      - "6379:6379"
    volumes:
      - basketdata:/data

  basket-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=basketdata
      - IdentityUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5105
      - LogstashUrl=http://logstash:31311
      - EventBusConnection=amqp://rabbitmq
      - EventBusRetryCount=5
      - EventBusRequestedHeartbeat=60
      - SupportedCultures=${SUPPORTED_CULTURES}
      - DefaultCulture=${DEFAULT_CULTURE}
    ports:
      - "5103:80"

  ordering-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sqldata;Database=OrderingDb;User Id=sa;Password=Gre@tPassw0rd
      - IdentityUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5105
      - LogstashUrl=http://logstash:31311
      - EventBusConnection=amqp://rabbitmq
      - EventBusRetryCount=5
      - EventBusRequestedHeartbeat=60
      - SupportedCultures=${SUPPORTED_CULTURES}
      - DefaultCulture=${DEFAULT_CULTURE}
      - SenderEmail=${SENDER_EMAIL}
      - SenderName=${SENDER_NAME}
      - SendGridApiKey=${SENDGRID_API_KEY}
      - MediaUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5131
      - ActionSendGridCustomOrderTemplateId=${SENDGRID_CUSTOM_ORDER_TEMPLATE_ID}
      - OrderStatuses=287ee71a-d87f-4563-833a-8e2771d1e5a5%26a73d4e41-1ff0-4eb5-929d-ed0aa1f52c2a%2610000%26New%26Erstellt%26Nowe%3B578480b3-15ef-492d-9f86-9827789c6804%2677e3aee6-6053-4d95-bbb5-fc2ebfa4f0de%2620000%26Processing%26In%20Bearbeitung%26W%20trakcie%20realizacji%3B3f48aaba-0ea5-4654-b753-4f3109f81bc5%26e071521b-682b-4a69-9070-be5782cbb223%2630000%26Complete%26Fertig%26Zrealizowane%3Bfc24e7e2-020b-4110-9415-7184ec837e71%26877d5f96-871f-406e-8d8b-d32bea48bf40%2640000%26Closed%26Abgeschlossen%26Zamkni%C4%99te%3B4fcdefc0-8181-490c-9378-fe96d234ccc9%265c192db0-af69-49b5-aebd-be1a02fc93ab%2650000%26Canceled%26Storniert%26Anulowane%3Be9fa4fc3-36c7-48ec-bf90-df9901867a38%26b2dc9bd0-444f-4e96-8708-715f7e416e18%2660000%26On%20Hold%26Gehalten%26Wstrzymane
    ports:
      - "5102:80"

  downloadcenter-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sqldata;Database=DownloadCenterDb;User Id=sa;Password=Gre@tPassw0rd
      - LogstashUrl=http://logstash:31311
      - SupportedCultures=${SUPPORTED_CULTURES}
      - DefaultCulture=${DEFAULT_CULTURE}
      - IdentityUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5105
      - EventBusConnection=amqp://rabbitmq
      - EventBusRetryCount=5
      - EventBusRequestedHeartbeat=60
      - OrganisationId=${ORGANISATION_ID}
    ports:
      - "5136:80"

  seller-web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ServerSideRenderingEndpoint=http://react-ssr:3000
      - ClientId=663bba90-0036-4a58-8516-39faa8baba87
      - ClientSecret=c61fcb32-cf9b-4cdd-84dc-4a1b173c36e9
      - CatalogUrl=http://catalog-api
      - BasketUrl=http://basket-api
      - ClientUrl=http://client-api
      - OrderUrl=http://ordering-api
      - InventoryUrl=http://inventory-api
      - NewsUrl=http://news-api
      - DownloadCenterUrl=http://downloadcenter-api
      - BuyerUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5107
      - MediaUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5131
      - IdentityUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5105
      - LogstashUrl=http://logstash:31311
      - SupportedCultures=${SUPPORTED_CULTURES}
      - DefaultCulture=${DEFAULT_CULTURE}
    ports:
      - "5104:80"

  buyer-web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ServerSideRenderingEndpoint=http://react-ssr:3000
      - ClientId=d9316849-7e98-4c5b-853b-5a322aecdc75
      - ClientSecret=693667b0-545e-48b6-9ef8-02ada81be946
      - CatalogUrl=http://catalog-api
      - MediaUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5131
      - IdentityUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5105
      - LogstashUrl=http://logstash:31311
      - InventoryUrl=http://inventory-api
      - OrderUrl=http://ordering-api
      - BasketUrl=http://basket-api
      - ClientUrl=http://client-api
      - NewsUrl=http://news-api
      - DownloadUrl=http://downloadcenter-api
      - MakeComplaintUrl=https://complaints.com
      - ProductAttributes=${PRODUCT_ATTRIBUTES}
      - OrganisationId=${ORGANISATION_ID}
      - SupportedCultures=${SUPPORTED_CULTURES}
      - DefaultCulture=${DEFAULT_CULTURE}
    ports:
      - "5107:80"

volumes:
  mssqldata:
    external: false
  basketdata:
    external: false
  azuritedata:
    external: false
  elasticsearchdata:
    driver: local