version: '3.8'

services:

  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5340:80"

  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"

  azurite:
    ports:
      - "10000:10000"
      - "10001:10001"

  react-ssr:
    environment: 
      NODE_ENV: development

  sqldata:
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Gre@tPassw0rd
    ports:
      - "5433:1433"
    volumes:
      - sqldata:/var/opt/mssql

  media-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sqldata;Database=MediaDb;User Id=sa;Password=Gre@tPassw0rd
      - StorageConnectionString=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;
      - FtpServerUrl=ftp://dawiddworak88-giuru:GreatPassw0rd@194.88.154.138
    depends_on:
      - azurite
    ports:
      - "5131:80"

  catalog-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sqldata;Database=CatalogDb;User Id=sa;Password=Gre@tPassw0rd
      - MediaApiClient=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5131
      - EventBusConnection=http://rabbitmq
      - PORT=80
      - PATH_BASE=/catalog-api
    ports:
      - "5101:80"

  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - MediaUrl=${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5131
      - ConnectionString=Server=sqldata;Database=IdentityDb;User Id=sa;Password=Gre@tPassw0rd
      - BasketApiClient=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5103
      - OrderingApiClient=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5102
    ports:
      - "5105:80"

  basketdata:
    ports:
      - "6379:6379"
    volumes:
      - basketdata:/data

  basket-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=http://basketdata
      - identityUrl=http://identity-api
      - IdentityUrlExternal=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5105
      - EventBusConnection=http://rabbitmq
      - PATH_BASE=/basket-api
      - PORT=80
    ports:
      - "5103:80"

  ordering-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=Server=sqldata;Database=OrderingDb;User Id=sa;Password=Gre@tPassw0rd
      - identityUrl=http://identity-api
      - IdentityUrlExternal=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5105
      - EventBusConnection=http://rabbitmq
      - CheckUpdateTime=30000
      - PATH_BASE=/ordering-api
      - PORT=80
    ports:
      - "5102:80"

  ordering-backgroundtasks:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=Server=sqldata;Database=OrderingDb;User Id=sa;Password=Gre@tPassw0rd
      - EventBusConnection=http://rabbitmq
      - CheckUpdateTime=30000
      - GracePeriodTime=1
    ports:
      - "5111:80"

  webshoppingagg:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - urls__basket=http://basket-api
      - urls__catalog=http://catalog-api
      - urls__orders=http://ordering-api
      - urls__identity=http://identity-api
      - urls__grpcBasket=http://basket-api:81
      - urls__grpcCatalog=http://catalog-api:81
      - urls__grpcOrdering=http://ordering-api:81
    ports:
    - "5203:80"
    - "15203:8001"

  ordering-signalrhub:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - EventBusConnection=http://rabbitmq
      - identityUrl=http://identity-api
    ports:
      - "5112:80"

  seller-web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - CatalogUrl=http://catalog-api
      - MediaUrl=${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5131
      - IdentityUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5105
      - SignalrHubUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5202
    ports:
      - "5104:80"

  buyer-web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ServerSideRenderingEndpoint=http://react-ssr:3000
      - CatalogUrl=http://catalog-api
      - MediaUrl=${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5131
      - IdentityUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5105
      - SignalrHubUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5202
    ports:
      - "5107:80"

volumes:
  sqldata:
    external: false
  basketdata:
    external: false
