version: '3.8'

services:

  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5340:80"

  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"

  azurite:
    ports:
      - "10000:10000"
      - "10001:10001"
    volumes:
      - azuritedata:/data

  elasticsearch:
    volumes:
      - elasticsearchdata:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.1
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:9200
    ports:
      - 5601:5601

  react-ssr:
    environment: 
      NODE_ENV: development

  sqldata:
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Gre@tPassw0rd
    ports:
      - "5433:1433"
    volumes:
      - mssqldata:/var/opt/mssql

  media-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sqldata;Database=MediaDb;User Id=sa;Password=Gre@tPassw0rd
      - StorageConnectionString=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;
    depends_on:
      - azurite
    ports:
      - "5131:80"

  catalog-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sqldata;Database=CatalogDb;User Id=sa;Password=Gre@tPassw0rd
      - MediaApiClient=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5131
      - EventBusConnection=http://rabbitmq
      - PORT=80
      - PATH_BASE=/catalog-api
    ports:
      - "5101:80"

  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ServerSideRenderingEndpoint=http://react-ssr:3000
      - CatalogUrl=http://catalog-api
      - MediaUrl=${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5131
      - ConnectionString=Server=sqldata;Database=IdentityDb;User Id=sa;Password=Gre@tPassw0rd
      - Clients=663bba90-0036-4a58-8516-39faa8baba87&c61fcb32-cf9b-4cdd-84dc-4a1b173c36e9&${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5104
      - Accounts=seller@user.com&Greg&Salesman&Gre@tPassw0rd&09affcc9-1665-45d6-919f-3d2026106ba1
      - Organisations=09affcc9-1665-45d6-919f-3d2026106ba1&ELTAP&eltap&eltap.com&True&EN&98daf0da-89ac-48db-8b9f-edc6383153ed
    ports:
      - "5105:80"

  basketdata:
    ports:
      - "6379:6379"
    volumes:
      - basketdata:/data

  basket-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=http://basketdata
      - identityUrl=http://identity-api
      - IdentityUrlExternal=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5105
      - EventBusConnection=http://rabbitmq
      - PATH_BASE=/basket-api
      - PORT=80
    ports:
      - "5103:80"

  ordering-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=Server=sqldata;Database=OrderingDb;User Id=sa;Password=Gre@tPassw0rd
      - identityUrl=http://identity-api
      - IdentityUrlExternal=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5105
      - EventBusConnection=http://rabbitmq
      - CheckUpdateTime=30000
      - PATH_BASE=/ordering-api
      - PORT=80
    ports:
      - "5102:80"

  ordering-backgroundtasks:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=Server=sqldata;Database=OrderingDb;User Id=sa;Password=Gre@tPassw0rd
      - EventBusConnection=http://rabbitmq
      - CheckUpdateTime=30000
      - GracePeriodTime=1
    ports:
      - "5111:80"

  webshoppingagg:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - urls__basket=http://basket-api
      - urls__catalog=http://catalog-api
      - urls__orders=http://ordering-api
      - urls__identity=http://identity-api
      - urls__grpcBasket=http://basket-api:81
      - urls__grpcCatalog=http://catalog-api:81
      - urls__grpcOrdering=http://ordering-api:81
    ports:
    - "5203:80"
    - "15203:8001"

  ordering-signalrhub:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - EventBusConnection=http://rabbitmq
      - identityUrl=http://identity-api
    ports:
      - "5112:80"

  seller-web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ServerSideRenderingEndpoint=http://react-ssr:3000
      - ClientId=663bba90-0036-4a58-8516-39faa8baba87
      - ClientSecret=c61fcb32-cf9b-4cdd-84dc-4a1b173c36e9
      - CatalogUrl=http://catalog-api
      - MediaUrl=${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5131
      - IdentityUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5105
      - SignalrHubUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5202
    ports:
      - "5104:80"

  buyer-web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ServerSideRenderingEndpoint=http://react-ssr:3000
      - CatalogUrl=http://catalog-api
      - MediaUrl=${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5131
      - IdentityUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5105
      - SignalrHubUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5202
    ports:
      - "5107:80"

volumes:
  mssqldata:
    external: false
  basketdata:
    external: false
  azuritedata:
    external: false
  elasticsearchdata:
    driver: local