version: '3.9'

services:

  grafana:
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./DockerServices/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./DockerServices/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"

  otel-collector:
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./DockerServices/otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"
      - "8888:8888"
      - "8889:8889"
      - "13133:13133"
      - "4317:4317"
      - "4318:4317"
      - "55679:55679"
    links:
      - jaeger
      - prometheus
      - loki

  prometheus:
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--enable-feature=remote-write-receiver'
      - '--storage.tsdb.retention.time=1d'
      - '--storage.tsdb.retention.size=1GB'
    ports:
      - "9090:9090"

  loki:
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  jaeger:
    environment:
      - SPAN_STORAGE_TYPE=memory
    command: --memory.max-traces=100000
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "16686:16686"

  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"

  azurite:
    ports:
      - "10000:10000"
      - "10001:10001"
    volumes:
      - azuritedata:/data

  elasticsearch:
    volumes:
      - elasticsearchdata:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200
      - 9300:9300

  seller-web-react-ssr:
    environment: 
      NODE_ENV: development
    volumes:
      - ../../fe/projects/Seller.Portal/server:/home/node/seller-web-react-ssr/server
      - ../../fe/projects/Seller.Portal/src:/home/node/seller-web-react-ssr/src

  buyer-web-react-ssr:
    environment: 
      NODE_ENV: development
    volumes:
      - ../../fe/projects/AspNetCore/server:/home/node/buyer-web-react-ssr/server
      - ../../fe/projects/AspNetCore/src:/home/node/buyer-web-react-ssr/src

  sqldata:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Gre@tPassw0rd
    ports:
      - "5433:1433"
    volumes:
      - mssqldata:/var/opt/mssql

  postgres:
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    logging:
        options:
          max-size: 10m
          max-file: "3"
    ports:
        - '5438:5432'
    volumes: 
        - postgresdata:/var/lib/postgresql/data
        - ./Project/Services/Content/Content.Api/scripts/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

  media-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sqldata;Database=MediaDb;User Id=sa;Encrypt=false;Password=Gre@tPassw0rd
      - RedisUrl=redis
      - StorageConnectionString=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;
      - IdentityUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5105
      - LogstashUrl=http://logstash:31311
      - SupportedCultures=${SUPPORTED_CULTURES}
      - DefaultCulture=${DEFAULT_CULTURE}
      - OrganisationId=${ORGANISATION_ID}
      - EventBusConnection=amqp://rabbitmq
      - EventBusRetryCount=5
      - EventBusRequestedHeartbeat=60
      - OpenTelemetryTracingCollectorUrl=http://otel-collector:4317
      - OpenTelemetryMetricsCollectorUrl=http://otel-collector:4317
      - OpenTelemetryLogsCollectorUrl=http://otel-collector:4317
    ports:
      - "5131:8080"

  client-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sqldata;Database=ClientDb;User Id=sa;Encrypt=false;Password=Gre@tPassw0rd
      - RedisUrl=redis
      - IdentityUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5105
      - LogstashUrl=http://logstash:31311
      - SupportedCultures=${SUPPORTED_CULTURES}
      - DefaultCulture=${DEFAULT_CULTURE}
      - SenderEmail=${SENDER_EMAIL}
      - SenderName=${SENDER_NAME}
      - SendGridApiKey=${SENDGRID_API_KEY}
      - ApplyRecipientEmail=office@eltap.com
      - ActionSendGridClientApplyConfirmationTemplateId=${SENDGRID_CLIENT_APPLY_CONFIRMATION_TEMPLATE_ID}
      - ActionSendGridClientApplyTemplateId=${SENDGRID_CLIENT_APPLY_TEMPLATE_ID}
      - OpenTelemetryTracingCollectorUrl=http://otel-collector:4317
      - OpenTelemetryMetricsCollectorUrl=http://otel-collector:4317
      - OpenTelemetryLogsCollectorUrl=http://otel-collector:4317
    ports:
      - "5133:8080"

  inventory-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sqldata;Database=InventoryDb;User Id=sa;Encrypt=false;Password=Gre@tPassw0rd
      - RedisUrl=redis
      - IdentityUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5105
      - LogstashUrl=http://logstash:31311
      - SupportedCultures=${SUPPORTED_CULTURES}
      - DefaultCulture=${DEFAULT_CULTURE}
      - EventBusConnection=amqp://rabbitmq
      - EventBusRetryCount=5
      - EventBusRequestedHeartbeat=60
      - OpenTelemetryTracingCollectorUrl=http://otel-collector:4317
      - OpenTelemetryMetricsCollectorUrl=http://otel-collector:4317
      - OpenTelemetryLogsCollectorUrl=http://otel-collector:4317
    ports:
      - "5134:8080"

  news-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sqldata;Database=NewsDb;User Id=sa;Encrypt=false;Password=Gre@tPassw0rd
      - RedisUrl=redis
      - IdentityUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5105
      - OpenTelemetryTracingCollectorUrl=http://otel-collector:4317
      - OpenTelemetryMetricsCollectorUrl=http://otel-collector:4317
      - OpenTelemetryLogsCollectorUrl=http://otel-collector:4317
      - SupportedCultures=${SUPPORTED_CULTURES}
      - DefaultCulture=${DEFAULT_CULTURE}
    ports:
      - "5135:8080"

  catalog-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sqldata;Database=CatalogDb;User Id=sa;Encrypt=false;Password=Gre@tPassw0rd
      - RedisUrl=redis
      - MediaUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5131
      - IdentityUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5105
      - EventBusConnection=amqp://rabbitmq
      - EventBusRetryCount=5
      - EventBusRequestedHeartbeat=60
      - ElasticsearchUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:9200
      - LogstashUrl=http://logstash:31311
      - ElasticsearchIndex=catalog
      - Brands=4a8f8442-43b0-4223-83bb-978d5e81acc7&ELTAP&09affcc9-1665-45d6-919f-3d2026106ba1
      - OpenTelemetryTracingCollectorUrl=http://otel-collector:4317
      - OpenTelemetryMetricsCollectorUrl=http://otel-collector:4317
      - OpenTelemetryLogsCollectorUrl=http://otel-collector:4317
      - SupportedCultures=${SUPPORTED_CULTURES}
      - DefaultCulture=${DEFAULT_CULTURE}
    ports:
      - "5101:8080"

  catalog-backgroundtasks:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sqldata;Database=CatalogDb;User Id=sa;Encrypt=false;Password=Gre@tPassw0rd
      - RedisUrl=redis
      - MediaUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5131
      - IdentityUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5105
      - EventBusConnection=amqp://rabbitmq
      - EventBusRetryCount=5
      - EventBusRequestedHeartbeat=60
      - ElasticsearchUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:9200
      - LogstashUrl=http://logstash:31311
      - ElasticsearchIndex=catalog
      - OpenTelemetryTracingCollectorUrl=http://otel-collector:4317
      - OpenTelemetryMetricsCollectorUrl=http://otel-collector:4317
      - OpenTelemetryLogsCollectorUrl=http://otel-collector:4317
      - SupportedCultures=${SUPPORTED_CULTURES}
      - DefaultCulture=${DEFAULT_CULTURE}
    ports:
      - "5132:8080"

  redis:
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  basket-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=redis
      - RedisUrl=redis
      - IdentityUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5105
      - EventBusConnection=amqp://rabbitmq
      - EventBusRetryCount=5
      - EventBusRequestedHeartbeat=60
      - OpenTelemetryTracingCollectorUrl=http://otel-collector:4317
      - OpenTelemetryMetricsCollectorUrl=http://otel-collector:4317
      - OpenTelemetryLogsCollectorUrl=http://otel-collector:4317
      - SupportedCultures=${SUPPORTED_CULTURES}
      - DefaultCulture=${DEFAULT_CULTURE}
    ports:
      - "5103:8080"

  ordering-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sqldata;Database=OrderingDb;User Id=sa;Encrypt=false;Password=Gre@tPassw0rd
      - RedisUrl=redis
      - IdentityUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5105
      - EventBusConnection=amqp://rabbitmq
      - EventBusRetryCount=5
      - EventBusRequestedHeartbeat=60
      - SupportedCultures=${SUPPORTED_CULTURES}
      - DefaultCulture=${DEFAULT_CULTURE}
      - SenderEmail=${SENDER_EMAIL}
      - SenderName=${SENDER_NAME}
      - SendGridApiKey=${SENDGRID_API_KEY}
      - MediaUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5131
      - ActionSendGridCustomOrderTemplateId=${SENDGRID_CUSTOM_ORDER_TEMPLATE_ID}
      - OrderStatuses=287ee71a-d87f-4563-833a-8e2771d1e5a5%26a73d4e41-1ff0-4eb5-929d-ed0aa1f52c2a%2610000%26New%26Erstellt%26Nowe%3B578480b3-15ef-492d-9f86-9827789c6804%2677e3aee6-6053-4d95-bbb5-fc2ebfa4f0de%2620000%26Processing%26In%20Bearbeitung%26W%20trakcie%20realizacji%3B3f48aaba-0ea5-4654-b753-4f3109f81bc5%26e071521b-682b-4a69-9070-be5782cbb223%2630000%26Complete%26Fertig%26Zrealizowane%3Bfc24e7e2-020b-4110-9415-7184ec837e71%26877d5f96-871f-406e-8d8b-d32bea48bf40%2640000%26Closed%26Abgeschlossen%26Zamkni%C4%99te%3B4fcdefc0-8181-490c-9378-fe96d234ccc9%265c192db0-af69-49b5-aebd-be1a02fc93ab%2650000%26Canceled%26Storniert%26Anulowane%3Be9fa4fc3-36c7-48ec-bf90-df9901867a38%26b2dc9bd0-444f-4e96-8708-715f7e416e18%2660000%26On%20Hold%26Gehalten%26Wstrzymane
      - OpenTelemetryTracingCollectorUrl=http://otel-collector:4317
      - OpenTelemetryMetricsCollectorUrl=http://otel-collector:4317
      - OpenTelemetryLogsCollectorUrl=http://otel-collector:4317
    ports:
      - "5102:8080"

  content-api:
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_NAME=postgres
      - DATABASE_HOST=host.docker.internal
      - DATABASE_PORT=5438
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_SSL=false
      - GIURU_API_SECRET=98daf0da-89ac-48db-8b9f-edc6383153ed
      - GIURU_API_EMAIL=seller@user.com
      - GIURU_API_ORGANISATION_ID=09affcc9-1665-45d6-919f-3d2026106ba1
      - GIURU_MEDIA_API_URL=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5131
      - GIURU_CONTENT_API_URL=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5111
      - GIURU_IDENTITY_API_URL=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5105/api/v1/token
    volumes:
      - ./Project/Services/Content/Content.Api/src:/content/src
    ports:
      - "5111:1337"

  downloadcenter-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sqldata;Database=DownloadCenterDb;User Id=sa;Encrypt=false;Password=Gre@tPassw0rd
      - RedisUrl=redis
      - SupportedCultures=${SUPPORTED_CULTURES}
      - DefaultCulture=${DEFAULT_CULTURE}
      - IdentityUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5105
      - EventBusConnection=amqp://rabbitmq
      - EventBusRetryCount=5
      - EventBusRequestedHeartbeat=60
      - OrganisationId=${ORGANISATION_ID}
      - OpenTelemetryTracingCollectorUrl=http://otel-collector:4317
      - OpenTelemetryMetricsCollectorUrl=http://otel-collector:4317
      - OpenTelemetryLogsCollectorUrl=http://otel-collector:4317
    ports:
      - "5136:8080"

  analytics-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sqldata;Database=AnalyticsDb;User Id=sa;Encrypt=false;Password=Gre@tPassw0rd
      - RedisUrl=redis
      - SupportedCultures=${SUPPORTED_CULTURES}
      - DefaultCulture=${DEFAULT_CULTURE}
      - IdentityUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5105
      - GiuruApiAppSecret=98daf0da-89ac-48db-8b9f-edc6383153ed
      - GiuruApiEmail=seller@user.com
      - GiuruApiOrganisationId=09affcc9-1665-45d6-919f-3d2026106ba1
      - GiuruTokenUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5105/api/v1/token
      - EventBusConnection=amqp://rabbitmq
      - EventBusRetryCount=5
      - EventBusRequestedHeartbeat=60
      - ClientUrl=http://client-api:8080
      - CatalogUrl=http://catalog-api:8080
      - GlobalUrl=http://global-api:8080
      - OpenTelemetryTracingCollectorUrl=http://otel-collector:4317
      - OpenTelemetryMetricsCollectorUrl=http://otel-collector:4317
      - OpenTelemetryLogsCollectorUrl=http://otel-collector:4317
    ports:
      - "5137:8080"

  global-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sqldata;Database=GlobalDb;User Id=sa;Encrypt=false;Password=Gre@tPassw0rd
      - RedisUrl=redis
      - SupportedCultures=${SUPPORTED_CULTURES}
      - OpenTelemetryTracingCollectorUrl=http://otel-collector:4317
      - OpenTelemetryMetricsCollectorUrl=http://otel-collector:4317
      - OpenTelemetryLogsCollectorUrl=http://otel-collector:4317
      - DefaultCulture=${DEFAULT_CULTURE}
      - IdentityUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5105
    ports:
      - "5138:8080"

  seller-web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ServerSideRenderingEndpoint=http://seller-web-react-ssr:3000
      - ClientId=663bba90-0036-4a58-8516-39faa8baba87
      - ClientSecret=c61fcb32-cf9b-4cdd-84dc-4a1b173c36e9
      - RedisUrl=redis
      - CatalogUrl=http://catalog-api:8080
      - BasketUrl=http://basket-api:8080
      - ClientUrl=http://client-api:8080
      - OrderUrl=http://ordering-api:8080
      - InventoryUrl=http://inventory-api:8080
      - NewsUrl=http://news-api:8080
      - SellerUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5104
      - DownloadCenterUrl=http://downloadcenter-api:8080
      - GlobalUrl=http://global-api:8080
      - AnalyticsUrl=http://analytics-api:8080
      - BuyerUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5107
      - MediaUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5131
      - IdentityUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5105
      - ContentUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5111
      - OpenTelemetryTracingCollectorUrl=http://otel-collector:4317
      - OpenTelemetryMetricsCollectorUrl=http://otel-collector:4317
      - OpenTelemetryLogsCollectorUrl=http://otel-collector:4317
      - SupportedCultures=${SUPPORTED_CULTURES}
      - DefaultCulture=${DEFAULT_CULTURE}
    volumes:
      - ./Project/Web/Buyer/Buyer.Web/wwwroot/dist:/src/wwwroot/dist
    ports:
      - "5104:8080"

  buyer-web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ServerSideRenderingEndpoint=http://buyer-web-react-ssr:3000
      - ClientId=d9316849-7e98-4c5b-853b-5a322aecdc75
      - ClientSecret=693667b0-545e-48b6-9ef8-02ada81be946
      - RedisUrl=redis
      - CatalogUrl=http://catalog-api:8080
      - MediaUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5131
      - IdentityUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5105
      - InventoryUrl=http://inventory-api:8080
      - OrderUrl=http://ordering-api:8080
      - BasketUrl=http://basket-api:8080
      - ClientUrl=http://client-api:8080
      - NewsUrl=http://news-api:8080
      - AnalyticsUrl=http://analytics-api:8080
      - ContentGraphQlUrl=http://content-api:1337/graphql
      - DownloadCenterUrl=http://downloadcenter-api:8080
      - ContentGraphQlAuthorizationKey=${STRAPI_AUTHORIZATION_KEY}
      - MakeComplaintUrl=https://complaints.com
      - ProductAttributes=${PRODUCT_ATTRIBUTES}
      - OrganisationId=${ORGANISATION_ID}
      - OpenTelemetryTracingCollectorUrl=http://otel-collector:4317
      - OpenTelemetryMetricsCollectorUrl=http://otel-collector:4317
      - OpenTelemetryLogsCollectorUrl=http://otel-collector:4317
      - SupportedCultures=${SUPPORTED_CULTURES}
      - DefaultCulture=${DEFAULT_CULTURE}
    volumes:
      - ./Project/Web/Seller/Seller.Web/wwwroot/dist:/src/wwwroot/dist
    ports:
      - "5107:8080"

volumes:
  mssqldata:
    external: false
  postgresdata:
    external: false
  redis:
    external: false
  azuritedata:
    external: false
  elasticsearchdata:
    driver: local
  grafana-data:
    external: false