apiVersion: v1
kind: Secret
metadata:
  name: b2b-analytics-api-secrets
type: Opaque
data:
  RedisUrl: {{ .Values.redisUrl | b64enc | quote }}
  ConnectionString: {{ .Values.analyticsApi.connectionString | b64enc | quote }}
  LogzIoToken: {{ .Values.logzIoToken | b64enc | quote }}
  EventBusConnection: {{ .Values.eventBusConnection | b64enc | quote }}
  GiuruApiAppSecret: {{ .Values.giuruApiSecret | b64enc | quote }}
  GiuruApiEmail: {{ .Values.giuruApiEmail | b64enc | quote }}
  GiuruApiOrganisationId: {{ .Values.giuruApiOrganisationId | b64enc | quote }}