FROM node:20.11.0-alpine

RUN apk update && apk add python3 make g++

RUN mkdir -p /home/node/seller-web-react-ssr/node_modules && chown -R node:node /home/node/seller-web-react-ssr

WORKDIR /home/node/seller-web-react-ssr

COPY package*.json ./

USER root

RUN npm install --legacy-peer-deps

USER node

COPY --chown=node:node . .

ENV NODE_ENV=development

EXPOSE 3000

CMD ["npm", "run", "watch-ssr"]