version: '3'
services:
  giuru-sql:
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Gre@tPassw0rd
    ports:
      - "9018:1433"
  seller-sql:
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Gre@tPassw0rd
    ports:
      - "9017:1433"
  seller-rabbitmq:
    image: rabbitmq
    restart: always
  seller-azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    restart: always
  react-ssr-web:
    build: 
      context: ../../fe
      dockerfile: Dockerfile-ssr-local
    image: react-ssr-web:react-ssr
    restart: always
    environment: 
      NODE_ENV: development
    ports:
      - "3000:3000"
  client-api:
    build: 
      context: ../../be
      dockerfile: Dockerfile-ClientApi
    image: client-api:client
    restart: always
    depends_on: 
      - react-ssr-web
    ports:
      - "44383:80"
  account-web:
    build: 
      context: ../../be
      dockerfile: Dockerfile-Account
    image: account-web:account
    restart: always
    depends_on: 
      - react-ssr-web
    ports:
      - "44325:80"