<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<OutputType>Library</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Grula.PricingIntelligencePlatform.Sdk" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\Infrastructure\Extensions\Foundation.Extensions\Foundation.Extensions.csproj" />
	</ItemGroup>

</Project>
