apiVersion: apps/v1
kind: Deployment
metadata:
  name: basket-api-deployment
  labels:
    app: basket-api
spec:
  replicas: {{ .Values.basketApi.replicas }}
  selector:
    matchLabels:
      app: basket-api
  template:
    metadata:
      labels:
        app: basket-api
    spec:
      containers:
      - name: basket-api-container
        image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        readinessProbe:
          httpGet:
            path: /hc
            port: 8080
          initialDelaySeconds: {{ .Values.basketApi.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.basketApi.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.basketApi.readinessProbe.timeoutSeconds }}
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8080
          initialDelaySeconds: {{ .Values.basketApi.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.basketApi.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.basketApi.livenessProbe.timeoutSeconds }}
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: {{ .Values.environment }}
        - name: LogzIoType
          value: {{ .Values.logzIoType }}
        - name: LogzIoDataCenterSubDomain
          value: {{ .Values.logzIoDataCenterSubDomain }}
        - name: OpenTelemetryCollectorUrl
          value: {{ .Values.openTelemetryCollectorUrl }}
        - name: IdentityUrl
          value: {{ .Values.identityUrl }}
        - name: EventBusRetryCount
          value: {{ .Values.eventBusRetryCount }}
        - name: EventBusRequestedHeartbeat
          value: {{ .Values.eventBusRequestedHeartbeat }}
        - name: DefaultCulture
          value: {{ .Values.defaultCulture }}
        - name: SupportedCultures
          value: {{ .Values.supportedCultures }}
        envFrom:
        - secretRef:
            name: b2b-basket-api-secrets
        ports:
        - containerPort: 8080