trigger: none

pr: none

resources:
  pipelines:
  - pipeline: ContentApiBuild
    source: '[Content Api] Build'
    trigger: 
      branches:
        include: 
        - main

variables:
- group: global
- template: './variables.yml'
- name: k8sReleaseName
  value: 'b2b-content-api'
- name: helmVersionToInstall
  value: '3.3.4'
- name: helmChartPath
  value: '$(Pipeline.Workspace)/helm-chart'

stages:
- stage: Production
  variables:
  - group: production
  - group: b2b-content-api-production
  jobs:
  - deployment:
    pool:
      vmImage: 'ubuntu-latest'
    environment: Production
    strategy:
      runOnce:
        deploy:
          steps:
          - task: ExtractFiles@1
            displayName: Extract Helm Chart
            inputs:
              archiveFilePatterns: '$(Pipeline.Workspace)/ContentApiBuild/drop/helm-chart.zip'
              destinationFolder: $(helmChartPath)
          - task: HelmInstaller@1
            displayName: Install Helm
            inputs:
              helmVersionToInstall: $(helmVersionToInstall)
          - task: HelmDeploy@0
            displayName: Login to Kubernetes
            inputs:
              command: login
              azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
              azureResourceGroup: $(azureResourceGroup)
              kubernetesCluster: $(kubernetesCluster)
          - script: |
              helm upgrade --install --wait \
              --set image.registry='$(acrLoginServer)' \
              --set image.repository='$(b2bContentApiImageRepository)' \
              --set image.tag='$(Resources.Pipeline.ContentApiBuild.RunID)' \
              --set environment='$(environment)' \
              --set tokenUrl='$(tokenUrl)' \
              --set mediaUrl='$(mediaUrl)' \
              --set contentUrl='$(contentUrl)' \
              --set giuruApiOrganisationId='$(giuruApiOrganisationId)' \
              --set giuruApiEmail='$(giuruApiEmail)' \
              --set giuruApiSecret='$(giuruApiSecret)' \
              --set contentApi.databaseClient='$(databaseClient)' \
              --set contentApi.databaseName='$(databaseName)' \
              --set contentApi.databaseHost='$(databaseHost)' \
              --set contentApi.databasePort='$(databasePort)' \
              --set contentApi.databaseUsername='$(databaseUsername)' \
              --set contentApi.databasePassword='$(databasePassword)' \
              --set contentApi.databaseSsl='$(databaseSsl)' \
              --set ingress.contentapidomain='$(contentApiDomain)' \
              $(k8sReleaseName) $(helmChartPath)
            displayName: Deploy to Kubernetes