apiVersion: v1
kind: Secret
metadata:
  name: b2b-global-api-secrets
type: Opaque
data:
  RedisUrl: {{ .Values.redisUrl | b64enc | quote }}
  ConnectionString: {{ .Values.globalApi.connectionString | b64enc | quote }}
  LogzIoToken: {{ .Values.logzIoToken | b64enc | quote }}