apiVersion: v1
kind: Secret
metadata:
  name: b2b-media-api-secrets
type: Opaque
data:
  RedisUrl: {{ .Values.redisUrl | b64enc | quote }}
  ConnectionString: {{ .Values.mediaApi.connectionString | b64enc | quote }}
  StorageConnectionString: {{ .Values.mediaApi.connectionString | b64enc | quote }}
  EventBusConnection: {{ .Values.eventBusConnection }}
  LogzIoToken: {{ .Values.logzIoToken | b64enc | quote }}