trigger:
  branches:
    include:
    - main
  paths:
    include:
    - be/src/Project/Services/Identity/Identity.Api

pr: none

variables:
- group: global
- group: production
- template: './variables.yml'
- name: b2bIdentityApiDockerfile
  value: 'be/src/Project/Services/Identity/Identity.Api/Dockerfile'
- name: dockerfileBuildContext
  value: 'be/src'
- name: chartPath
  value: 'misc/deployment/IdentityApi/helm-chart'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    token=BUILD_ID
    sed -i "s/$token/$(Build.BuildId)/g" $(chartPath)/Chart.yaml
  displayName: Set the Helm Chart appversion
- task: ArchiveFiles@2
  displayName: Zip the Helm Chart
  inputs:
    rootFolderOrFile: $(chartPath)
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/helm-chart.zip'
- task: Docker@2
  displayName: Build and Push Docker Image
  inputs:
    command: buildAndPush
    repository: $(b2bIdentityApiImageRepository)
    dockerfile: $(b2bIdentityApiDockerfile)
    buildContext: $(dockerfileBuildContext)
    containerRegistry: $(acrServiceConnection)
    tags: |
      $(Build.BuildId)
- task: PublishBuildArtifacts@1
  displayName: Publish artifacts to staging directory
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)