trigger:
  branches:
    include:
    - main
  paths:
    include:
    - be/src/Project/Services/Identity/Identity.Api

pr: none

variables:
- group: global
- group: production
- template: './variables.yml'
- name: b2bIdentityApiDockerfile
  value: 'be/src/Project/Services/Identity/Identity.Api/Dockerfile'
- name: dockerfileWebsiteBuildContext
  value: 'be/src'
- name: b2bAccountWebSsrDockerfile
  value: 'fe/projects/Account/Dockerfile-ssr'
- name: dockerfileSsrBuildContext
  value: 'fe/projects/Account'
- name: chartPath
  value: 'misc/deployment/IdentityApi/helm-chart'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    token=BUILD_ID
    sed -i "s/$token/$(Build.BuildId)/g" $(chartPath)/Chart.yaml
  displayName: Set the Helm Chart appversion
- task: ArchiveFiles@2
  displayName: Zip the Helm Chart
  inputs:
    rootFolderOrFile: $(chartPath)
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/helm-chart.zip'
- task: Npm@1
  displayName: Install Website Dependencies
  inputs:
    command: custom
    verbose: false
    customCommand: 'install --legacy-peer-deps'
- task: Npm@1
  displayName: Build Website
  inputs:
    command: custom
    verbose: false
    customCommand: 'run build-fe'
- task: Docker@2
  displayName: Build and Push Docker Image for Website
  inputs:
    command: buildAndPush
    repository: $(b2bIdentityApiImageRepository)
    dockerfile: $(b2bIdentityApiDockerfile)
    buildContext: $(dockerfileWebsiteBuildContext)
    containerRegistry: $(acrServiceConnection)
    tags: |
      $(Build.BuildId)
- task: Docker@2
  displayName: Build and Push Docker Image for SSR
  inputs:
    command: buildAndPush
    repository: $(b2bAccountWebReactSsrImageRepository)
    dockerfile: $(b2bAccountWebSsrDockerfile)
    buildContext: $(dockerfileSsrBuildContext)
    containerRegistry: $(acrServiceConnection)
- task: PublishBuildArtifacts@1
  displayName: Publish artifacts to staging directory
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)