environment: "#{Environment}#"
identityUrl: "#{IdentityUrl}#"
redisUrl: "#{RedisUrl}#"
mediaUrl: "#{MediaUrl}#"
cdnUrl: "#{CdnUrl}#"
catalogUrl: "#{CatalogUrl}#"
inventoryUrl: "#{InventoryUrl}#"
orderUrl: "#{OrderUrl}#"
basketUrl: "#{BasketUrl}#"
clientUrl: "#{ClientUrl}#"
newsUrl: "#{NewsUrl}#"
analyticsUrl: "#{AnalyticsUrl}#"
contentGraphQlUrl: "#{ContentGraphQlUrl}#"
downloadCenterUrl: "#{DownloadCenterUrl}#"
makeComplaintUrl: "#{MakeComplaintUrl}#"
organisationId: "#{OrganisationId}#"
serverSideRenderingEndpoint: "#{ServerSideRenderingEndpoint}#"
contentGraphQlAuthorizationKey: "#{ContentGraphQlAuthorizationKey}#"
logzIoToken: "#{LogzIoToken}#"
logzIoType: "#{LogzIoType}#"
logzIoDataCenterSubDomain: "#{LogzIoDataCenterSubDomain}#"
openTelemetryCollectorUrl: "#{OpenTelemetryCollectorUrl}#"
supportedCultures: "en,de,pl"
defaultCulture: "en"
buyerWeb:
  clientId: "#{BuyerWeb--ClientId}#"
  clientSecret: "#{BuyerWeb--ClientSecret}#"
  productAttributes: "#{BuyerWeb--ProductAttributes}#"
  googleTagManagerIdentifier: "#{BuyerWeb--GoogleTagManagerIdentifier}#"
  replicas: "1"
  readinessProbe:
    initialDelaySeconds: "15"
    periodSeconds: "30"
    timeoutSeconds: "15"
  livenessProbe:
    initialDelaySeconds: "15"
    periodSeconds: "30"
    timeoutSeconds: "15"