apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-ssr-web-deployment
  namespace: ingress-basic
  labels:
    app: react-ssr-web
spec:
  selector:
    matchLabels:
      app: react-ssr-web
  template:
    metadata:
      labels:
        app: react-ssr-web
    spec:
      containers:
      - name: react-ssr-web-container
        image: giuru.azurecr.io/react-ssr-web:{{ .Values.image.tag }}
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: giurusecret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetcore-web-deployment
  namespace: ingress-basic
  labels:
    app: aspnetcore-web
spec:
  selector:
    matchLabels:
      app: aspnetcore-web
  template:
    metadata:
      labels:
        app: aspnetcore-web
    spec:
      containers:
      - name: aspnetcore-web-container
        image: giuru.azurecr.io/aspnetcore-web:{{ .Values.image.tag }}
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: giurusecret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-web-deployment
  namespace: ingress-basic
  labels:
    app: account-web
spec:
  selector:
    matchLabels:
      app: account-web
  template:
    metadata:
      labels:
        app: account-web
    spec:
      containers:
      - name: account-web-container
        image: giuru.azurecr.io/account-web:{{ .Values.image.tag }}
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: giurusecret