apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-api-deployment
  labels:
    app: media-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: media-api
  template:
    metadata:
      labels:
        app: media-api
    spec:
      containers:
      - name: media-api-container
        image: {{ .Values.image.registry }}/media-api:{{ .Values.image.tag }}
        resources:
          limits:
            memory: "1800Mi"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: {{ .Values.environment }}
        - name: ConnectionString
          value: {{ .Values.mediaApi.connectionString }}
        - name: StorageConnectionString
          value: {{ .Values.mediaApi.storageConnectionString }}
        - name: IdentityUrl
          value: {{ .Values.identityUrl }}
        - name: LogzIoToken
          value: {{ .Values.logzIoToken }}
        - name: LogzIoType
          value: {{ .Values.logzIoType }}
        - name: LogzIoDataCenterSubDomain
          value: {{ .Values.logzIoDataCenterSubDomain }}
        - name: DefaultCulture
          value: {{ .Values.defaultCulture }}
        - name: SupportedCultures
          value: {{ .Values.supportedCultures }}
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-api-deployment
  labels:
    app: client-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-api
  template:
    metadata:
      labels:
        app: client-api
    spec:
      containers:
      - name: client-api-container
        image: {{ .Values.image.registry }}/client-api:{{ .Values.image.tag }}
        resources:
          limits:
            memory: "250Mi"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: {{ .Values.environment }}
        - name: ConnectionString
          value: {{ .Values.clientApi.connectionString }}
        - name: IdentityUrl
          value: {{ .Values.identityUrl }}
        - name: LogzIoToken
          value: {{ .Values.logzIoToken }}
        - name: LogzIoType
          value: {{ .Values.logzIoType }}
        - name: LogzIoDataCenterSubDomain
          value: {{ .Values.logzIoDataCenterSubDomain }}
        - name: DefaultCulture
          value: {{ .Values.defaultCulture }}
        - name: SupportedCultures
          value: {{ .Values.supportedCultures }}
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api-deployment
  labels:
    app: catalog-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      containers:
      - name: catalog-api-container
        image: {{ .Values.image.registry }}/catalog-api:{{ .Values.image.tag }}
        resources:
          limits:
            memory: "500Mi"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: {{ .Values.environment }}
        - name: ConnectionString
          value: {{ .Values.catalogApi.connectionString }}
        - name: IdentityUrl
          value: {{ .Values.identityUrl }}
        - name: EventBusConnection
          value: {{ .Values.eventBusConnection }}
        - name: EventBusRetryCount
          value: {{ .Values.eventBusRetryCount }}
        - name: MediaUrl
          value: {{ .Values.mediaUrl }}
        - name: ElasticsearchUrl
          value: {{ .Values.elasticsearchUrl }}
        - name: ElasticsearchIndex
          value: {{ .Values.catalogApi.elasticsearchIndex }}
        - name: Brands
          value: {{ .Values.catalogApi.brands }}
        - name: LogzIoToken
          value: {{ .Values.logzIoToken }}
        - name: LogzIoType
          value: {{ .Values.logzIoType }}
        - name: LogzIoDataCenterSubDomain
          value: {{ .Values.logzIoDataCenterSubDomain }}
        - name: DefaultCulture
          value: {{ .Values.defaultCulture }}
        - name: SupportedCultures
          value: {{ .Values.supportedCultures }}
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-backgroundtasks-deployment
  labels:
    app: catalog-backgroundtasks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-backgroundtasks
  template:
    metadata:
      labels:
        app: catalog-backgroundtasks
    spec:
      containers:
      - name: catalog-backgroundtasks-container
        image: {{ .Values.image.registry }}/catalog-backgroundtasks:{{ .Values.image.tag }}
        resources:
          limits:
            memory: "250Mi"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: {{ .Values.environment }}
        - name: ConnectionString
          value: {{ .Values.catalogApi.connectionString }}
        - name: IdentityUrl
          value: {{ .Values.identityUrl }}
        - name: EventBusConnection
          value: {{ .Values.eventBusConnection }}
        - name: EventBusRetryCount
          value: {{ .Values.eventBusRetryCount }}
        - name: ElasticsearchUrl
          value: {{ .Values.elasticsearchUrl }}
        - name: ElasticsearchIndex
          value: {{ .Values.catalogApi.elasticsearchIndex }}
        - name: LogzIoToken
          value: {{ .Values.logzIoToken }}
        - name: LogzIoType
          value: {{ .Values.logzIoType }}
        - name: LogzIoDataCenterSubDomain
          value: {{ .Values.logzIoDataCenterSubDomain }}
        - name: DefaultCulture
          value: {{ .Values.defaultCulture }}
        - name: SupportedCultures
          value: {{ .Values.supportedCultures }}
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basket-api-deployment
  labels:
    app: basket-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basket-api
  template:
    metadata:
      labels:
        app: basket-api
    spec:
      containers:
      - name: basket-api-container
        image: {{ .Values.image.registry }}/basket-api:{{ .Values.image.tag }}
        resources:
          limits:
            memory: "250Mi"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: {{ .Values.environment }}
        - name: ConnectionString
          value: {{ .Values.basketApi.connectionString }}
        - name: IdentityUrl
          value: {{ .Values.identityUrl }}
        - name: EventBusConnection
          value: {{ .Values.eventBusConnection }}
        - name: EventBusRetryCount
          value: {{ .Values.eventBusRetryCount }}
        - name: LogzIoToken
          value: {{ .Values.logzIoToken }}
        - name: LogzIoType
          value: {{ .Values.logzIoType }}
        - name: LogzIoDataCenterSubDomain
          value: {{ .Values.logzIoDataCenterSubDomain }}
        - name: DefaultCulture
          value: {{ .Values.defaultCulture }}
        - name: SupportedCultures
          value: {{ .Values.supportedCultures }}
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordering-api-deployment
  labels:
    app: ordering-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordering-api
  template:
    metadata:
      labels:
        app: ordering-api
    spec:
      containers:
      - name: ordering-api-container
        image: {{ .Values.image.registry }}/ordering-api:{{ .Values.image.tag }}
        resources:
          limits:
            memory: "250Mi"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: {{ .Values.environment }}
        - name: ConnectionString
          value: {{ .Values.orderingApi.connectionString }}
        - name: IdentityUrl
          value: {{ .Values.identityUrl }}
        - name: EventBusConnection
          value: {{ .Values.eventBusConnection }}
        - name: EventBusRetryCount
          value: {{ .Values.eventBusRetryCount }}
        - name: SenderEmail
          value: {{ .Values.senderEmail }}
        - name: SenderName
          value: {{ .Values.senderName }}
        - name: SendGridApiKey
          value: {{ .Values.sendGridApiKey }}
        - name: LogzIoToken
          value: {{ .Values.logzIoToken }}
        - name: LogzIoType
          value: {{ .Values.logzIoType }}
        - name: LogzIoDataCenterSubDomain
          value: {{ .Values.logzIoDataCenterSubDomain }}
        - name: DefaultCulture
          value: {{ .Values.defaultCulture }}
        - name: SupportedCultures
          value: {{ .Values.supportedCultures }}
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-ssr-web-deployment
  labels:
    app: react-ssr-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-ssr-web
  template:
    metadata:
      labels:
        app: react-ssr-web
    spec:
      containers:
      - name: react-ssr-web-container
        image: {{ .Values.image.registry }}/react-ssr-web:{{ .Values.image.tag }}
        resources:
          limits:
            memory: "1000Mi"
        env:
        - name: NODE_ENV
          value: {{ .Values.nodeEnvironment }}
        ports:
        - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-api-deployment
  labels:
    app: identity-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-api
  template:
    metadata:
      labels:
        app: identity-api
    spec:
      containers:
      - name: identity-api-container
        image: {{ .Values.image.registry }}/identity-api:{{ .Values.image.tag }}
        resources:
          limits:
            memory: "250Mi"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: {{ .Values.environment }}
        - name: ServerSideRenderingEndpoint
          value: {{ .Values.serverSideRenderingEndpoint }}
        - name: ConnectionString
          value: {{ .Values.identityApi.connectionString }}
        - name: CatalogUrl
          value: {{ .Values.catalogUrl }}
        - name: MediaUrl
          value: {{ .Values.mediaUrl }}
        - name: IdentityUrl
          value: {{ .Values.identityUrl }}
        - name: Clients
          value: {{ .Values.identityApi.clients }}
        - name: SellerClientId
          value: {{ .Values.identityApi.sellerClientId }}
        - name: Accounts
          value: {{ .Values.identityApi.accounts }}
        - name: Organisations
          value: {{ .Values.identityApi.organisations }}
        - name: PrivacyPolicy
          value: {{ .Values.identityApi.privacyPolicy }}
        - name: Regulations
          value: {{ .Values.identityApi.regulations }}
        - name: AzureKeyVaultGiuruIdentityServer4Certificate
          value: {{ .Values.identityApi.azureKeyVaultGiuruIdentityServer4Certificate }}
        - name: AzureKeyVaultGiuruIdentityServer4CertificatePassword
          value: {{ .Values.identityApi.azureKeyVaultGiuruIdentityServer4CertificatePassword }}
        - name: AzureKeyVaultClientId
          value: {{ .Values.identityApi.azureKeyVaultClientId }}
        - name: AzureKeyVaultClientSecret
          value: {{ .Values.identityApi.azureKeyVaultClientSecret }}
        - name: SendGridApiKey
          value: {{ .Values.sendGridApiKey }}
        - name: SenderEmail
          value: {{ .Values.senderEmail }}
        - name: SenderName
          value: {{ .Values.senderName }}
        - name: ActionSendGridCreateTemplateId
          value: {{ .Values.identityApi.actionSendGridCreateTemplateId }}
        - name: ActionSendGridResetTemplateId
          value: {{ .Values.identityApi.actionSendGridResetTemplateId }}
        - name: LogzIoToken
          value: {{ .Values.logzIoToken }}
        - name: LogzIoType
          value: {{ .Values.logzIoType }}
        - name: LogzIoDataCenterSubDomain
          value: {{ .Values.logzIoDataCenterSubDomain }}
        - name: DefaultCulture
          value: {{ .Values.defaultCulture }}
        - name: SupportedCultures
          value: {{ .Values.supportedCultures }}
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-api-deployment
  labels:
    app: inventory-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-api
  template:
    metadata:
      labels:
        app: inventory-api
    spec:
      containers:
      - name: inventory-api-container
        image: {{ .Values.image.registry }}/inventory-api:{{ .Values.image.tag }}
        resources:
          limits:
            memory: "250Mi"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: {{ .Values.environment }}
        - name: ConnectionString
          value: {{ .Values.inventoryApi.connectionString }}
        - name: IdentityUrl
          value: {{ .Values.identityUrl }}
        - name: EventBusConnection
          value: {{ .Values.eventBusConnection }}
        - name: EventBusRetryCount
          value: {{ .Values.eventBusRetryCount }}
        - name: LogzIoToken
          value: {{ .Values.logzIoToken }}
        - name: LogzIoType
          value: {{ .Values.logzIoType }}
        - name: LogzIoDataCenterSubDomain
          value: {{ .Values.logzIoDataCenterSubDomain }}
        - name: DefaultCulture
          value: {{ .Values.defaultCulture }}
        - name: SupportedCultures
          value: {{ .Values.supportedCultures }}
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-api-deployment
  labels:
    app: news-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news-api
  template:
    metadata:
      labels:
        app: news-api
    spec:
      containers:
      - name: news-api-container
        image: {{ .Values.image.registry }}/news-api:{{ .Values.image.tag }}
        resources:
          limits:
            memory: "250Mi"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: {{ .Values.environment }}
        - name: ConnectionString
          value: {{ .Values.newsApi.connectionString }}
        - name: IdentityUrl
          value: {{ .Values.identityUrl }}
        - name: CdnUrl
          value: {{ .Values.cdnUrl }}
        - name: EventBusConnection
          value: {{ .Values.eventBusConnection }}
        - name: EventBusRetryCount
          value: {{ .Values.eventBusRetryCount }}
        - name: LogzIoToken
          value: {{ .Values.logzIoToken }}
        - name: LogzIoType
          value: {{ .Values.logzIoType }}
        - name: LogzIoDataCenterSubDomain
          value: {{ .Values.logzIoDataCenterSubDomain }}
        - name: DefaultCulture
          value: {{ .Values.defaultCulture }}
        - name: SupportedCultures
          value: {{ .Values.supportedCultures }}
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: buyer-web-deployment
  labels:
    app: buyer-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buyer-web
  template:
    metadata:
      labels:
        app: buyer-web
    spec:
      containers:
      - name: buyer-web-container
        image: {{ .Values.image.registry }}/buyer-web:{{ .Values.image.tag }}
        resources:
          limits:
            memory: "250Mi"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: {{ .Values.environment }}
        - name: OrganisationId
          value: {{ .Values.organisationId }}
        - name: ServerSideRenderingEndpoint
          value: {{ .Values.serverSideRenderingEndpoint }}
        - name: CatalogUrl
          value: {{ .Values.catalogUrl }}
        - name: MediaUrl
          value: {{ .Values.mediaUrl }}
        - name: IdentityUrl
          value: {{ .Values.identityUrl }}
        - name: InventoryUrl
          value: {{ .Values.inventoryUrl }}
        - name: ClientUrl
          value: {{ .Values.clientUrl }}
        - name: BasketUrl
          value: {{ .Values.basketUrl }}
        - name: OrderUrl
          value: {{ .Values.orderUrl }}
        - name: NewsUrl
          value: {{ .Values.newsUrl }}
        - name: MakeComplaintUrl
          value: {{ .Values.makeComplaintUrl }}
        - name: CdnUrl
          value: {{ .Values.cdnUrl }}
        - name: ClientId
          value: {{ .Values.buyerWeb.clientId }}
        - name: ClientSecret
          value: {{ .Values.buyerWeb.clientSecret }}
        - name: LogzIoToken
          value: {{ .Values.logzIoToken }}
        - name: LogzIoType
          value: {{ .Values.logzIoType }}
        - name: LogzIoDataCenterSubDomain
          value: {{ .Values.logzIoDataCenterSubDomain }}
        - name: GoogleTagManagerIdentifier
          value: {{ .Values.googleTagManagerIdentifier }}
        - name: DefaultCulture
          value: {{ .Values.defaultCulture }}
        - name: SupportedCultures
          value: {{ .Values.supportedCultures }}
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seller-web-deployment
  labels:
    app: seller-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seller-web
  template:
    metadata:
      labels:
        app: seller-web
    spec:
      containers:
      - name: seller-web-container
        image: {{ .Values.image.registry }}/seller-web:{{ .Values.image.tag }}
        resources:
          limits:
            memory: "250Mi"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: {{ .Values.environment }}
        - name: ServerSideRenderingEndpoint
          value: {{ .Values.serverSideRenderingEndpoint }}
        - name: CatalogUrl
          value: {{ .Values.catalogUrl }}
        - name: MediaUrl
          value: {{ .Values.mediaUrl }}
        - name: IdentityUrl
          value: {{ .Values.identityUrl }}
        - name: OrderUrl
          value: {{ .Values.orderUrl }}
        - name: BasketUrl
          value: {{ .Values.basketUrl }}
        - name: ClientUrl
          value: {{ .Values.clientUrl }}
        - name: InventoryUrl
          value: {{ .Values.inventoryUrl }}
        - name: NewsUrl
          value: {{ .Values.newsUrl }}
        - name: BuyerUrl
          value: {{ .Values.buyerUrl }}
        - name: ClientId
          value: {{ .Values.sellerWeb.clientId }}
        - name: ClientSecret
          value: {{ .Values.sellerWeb.clientSecret }}
        - name: LogzIoToken
          value: {{ .Values.logzIoToken }}
        - name: LogzIoType
          value: {{ .Values.logzIoType }}
        - name: LogzIoDataCenterSubDomain
          value: {{ .Values.logzIoDataCenterSubDomain }}
        - name: DefaultCulture
          value: {{ .Values.defaultCulture }}
        - name: SupportedCultures
          value: {{ .Values.supportedCultures }}
        ports:
        - containerPort: 80