apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-ssr-web-deployment
  labels:
    app: react-ssr-web
spec:
  selector:
    matchLabels:
      app: react-ssr-web
  template:
    metadata:
      labels:
        app: react-ssr-web
    spec:
      containers:
      - name: react-ssr-web-container
        image: {{ .Values.image.registry }}/react-ssr-web:{{ .Values.image.tag }}
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: giurusecret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetcore-web-deployment
  labels:
    app: aspnetcore-web
spec:
  selector:
    matchLabels:
      app: aspnetcore-web
  template:
    metadata:
      labels:
        app: aspnetcore-web
    spec:
      containers:
      - name: aspnetcore-web-container
        image: {{ .Values.image.registry }}/aspnetcore-web:{{ .Values.image.tag }}
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: giurusecret