apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: giuru-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/proxy-buffers: "4 256k"
    nginx.ingress.kubernetes.io/proxy-busy-buffers-size: "256k"
    nginx.ingress.kubernetes.io/client-header-buffer-size: "64k"
    nginx.ingress.kubernetes.io/http2-max-field-size: "16k"
    nginx.ingress.kubernetes.io/http2-max-header-size: "128k"
    nginx.ingress.kubernetes.io/large-client-header-buffers: "8 64k"
    nginx.ingress.kubernetes.io/proxy-body-size: "500m"
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.clientapidomain }}
    - {{ .Values.ingress.basketapidomain }}
    - {{ .Values.ingress.orderingapidomain }}
    - {{ .Values.ingress.mediaapidomain }}
    - {{ .Values.ingress.identityapidomain }}
    - {{ .Values.ingress.inventoryapidomain }}
    - {{ .Values.ingress.newsapidomain }}
    - {{ .Values.ingress.catalogapidomain }}
    - {{ .Values.ingress.buyerapidomain }}
    - {{ .Values.ingress.sellerapidomain }}
    secretName: tls-secret
  rules:
  - host: {{ .Values.ingress.mediaapidomain }}
    http:
      paths:
      - backend:
          serviceName: media-api-service
          servicePort: 80
        path: /
  - host: {{ .Values.ingress.clientapidomain }}
    http:
      paths:
      - backend:
          serviceName: client-api-service
          servicePort: 80
        path: /
  - host: {{ .Values.ingress.basketapidomain }}
    http:
      paths:
      - backend:
          serviceName: basket-api-service
          servicePort: 80
        path: /
  - host: {{ .Values.ingress.orderingapidomain }}
    http:
      paths:
      - backend:
          serviceName: ordering-api-service
          servicePort: 80
        path: /
  - host: {{ .Values.ingress.identityapidomain }}
    http:
      paths:
      - backend:
          serviceName: identity-api-service
          servicePort: 80
        path: /
  - host: {{ .Values.ingress.catalogapidomain }}
    http:
      paths:
      - backend:
          serviceName: catalog-api-service
          servicePort: 80
        path: /
  - host: {{ .Values.ingress.inventoryapidomain }}
    http:
      paths:
      - backend:
          serviceName: inventory-api-service
          servicePort: 80
        path: /
  - host: {{ .Values.ingress.newsapidomain }}
    http:
      paths:
      - backend:
          serviceName: news-api-service
          servicePort: 80
        path: /
  - host: {{ .Values.ingress.buyerapidomain }}
    http:
      paths:
      - backend:
          serviceName: buyer-web-service
          servicePort: 80
        path: /
  - host: {{ .Values.ingress.sellerapidomain }}
    http:
      paths:
      - backend:
          serviceName: seller-web-service
          servicePort: 80
        path: /