apiVersion: v1
kind: Secret
metadata:
  name: b2b-content-api-secrets
type: Opaque
data:
  DATABASE_PASSWORD: {{ .Values.contentApi.databasePassword | b64enc | quote }}
  GIURU_API_SECRET: {{ .Values.giuruApiSecret | b64enc | quote }}