apiVersion: v1
kind: Secret
metadata:
  name: b2b-content-api-secrets
type: Opaque
data:
  DATABASE_PASSWORD: {{ .Values.contentApi.databasePassword | b64enc | quote }}
  DATABASE_CLIENT: {{ .Values.contentApi.databaseClient | b64enc | quote }}
  DATABASE_HOST: {{ .Values.contentApi.databaseHost | b64enc | quote }}
  DATABASE_NAME: {{ .Values.contentApi.databaseName | b64enc | quote }}
  DATABASE_USERNAME: {{ .Values.contentApi.databaseUsername | b64enc | quote }}
  DATABASE_PORT: {{ .Values.contentApi.databasePort | b64enc | quote }}
  DATABASE_SSL: {{ .Values.contentApi.databaseSsl | b64enc | quote }}
  GIURU_API_ORGANISATION_ID: {{ .Values.giuruApiOrganisationId | b64enc | quote }}
  GIURU_API_EMAIL: {{ .Values.giuruApiEmail | b64enc | quote }}
  GIURU_API_SECRET: {{ .Values.giuruApiSecret | b64enc | quote }}