trigger: none

pr: none

resources:
  pipelines:
  - pipeline: DownloadCenterApiBuild
    source: '[Download Center Api] Build'
    trigger: 
      branches:
        include: 
        - main

variables:
- group: global
- template: './variables.yml'
- name: k8sReleaseName
  value: 'b2b-downloadcenter-api'
- name: helmVersionToInstall
  value: '3.3.4'
- name: helmChartPath
  value: '$(Pipeline.Workspace)/helm-chart'

stages:
- stage: Production
  variables:
  - group: production
  - group: b2b-downloadcenter-api-production
  jobs:
  - deployment:
    pool:
      vmImage: 'ubuntu-latest'
    environment: Production
    strategy:
      runOnce:
        deploy:
          steps:
          - task: ExtractFiles@1
            displayName: Extract Helm Chart
            inputs:
              archiveFilePatterns: '$(Pipeline.Workspace)/DownloadCenterApiBuild/drop/helm-chart.zip'
              destinationFolder: $(helmChartPath)
          - task: HelmInstaller@1
            displayName: Install Helm
            inputs:
              helmVersionToInstall: $(helmVersionToInstall)
          - task: HelmDeploy@0
            displayName: Login to Kubernetes
            inputs:
              command: login
              azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
              azureResourceGroup: $(azureResourceGroup)
              kubernetesCluster: $(kubernetesCluster)
          - script: |
              stringConnectionString="$(connectionString)"
              escapedConnectionString=${stringConnectionString//,/\\,}

              helm upgrade --install --wait \
              --set image.registry='$(acrLoginServer)' \
              --set image.repository='$(b2bDownloadCenterApiImageRepository)' \
              --set image.tag='$(Resources.Pipeline.DownloadCenterApiBuild.RunID)' \
              --set environment='$(environment)' \
              --set identityUrl='$(identityUrl)' \
              --set redisUrl='$(redisUrl)' \
              --set logzIoToken='$(logzIoToken)' \
              --set logzIoType='$(logzIoType)' \
              --set organisationId='$(organisationId)' \
              --set eventBusConnection='$(eventBusConnection)' \
              --set eventBusRetryCount=`$(eventBusRetryCount)` \
              --set eventBusRequestedHeartbeat=`$(eventBusRequestedHeartbeat)` \
              --set logzIoDataCenterSubDomain='$(logzIoDataCenterSubDomain)' \
              --set openTelemetryCollectorUrl='$(openTelemetryCollectorUrl)' \
              --set downloadCenterApi.connectionString="$escapedConnectionString" \
              --set ingress.downloadcenterapidomain='$(downloadCenterApiDomain)' \
              $(k8sReleaseName) $(helmChartPath)
            displayName: Deploy to Kubernetes