#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/sdk:3.1.301 AS build-env
WORKDIR /app

COPY ./src/Infrastructure ./Infrastructure/
COPY ./src/Feature ./Feature/
COPY ./src/Project/Web/Seller.Portal ./Project/Web/Seller.Portal/
RUN dotnet publish ./Project/Web/Seller.Portal/Seller.Portal.csproj -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1.5
WORKDIR /app
COPY --from=build-env /app/out .

ENTRYPOINT ["dotnet", "Seller.Portal.dll"]