#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/sdk:3.1.102 AS build-env
WORKDIR /app

COPY ./src/Infrastructure ./Infrastructure/
COPY ./src/Feature ./Feature/
COPY ./src/Project/Web/Tenant.Portal ./Project/Web/Tenant.Portal/
RUN dotnet publish ./Project/Web/Tenant.Portal/Tenant.Portal.csproj -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1.2
WORKDIR /app
COPY --from=build-env /app/out .

ENTRYPOINT ["dotnet", "Tenant.Portal.dll"]