name: Analytics-Api Test Deployment
run-name: ${{ github.actor }} is deploying Analytics-Api to Test environment 🚀

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Analytics-Api Continuous Integration"]
    branches: [develop]
    types: [completed]

concurrency:
  group: cd-giuru-test
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

jobs:
  Build-and-Deploy-Docker-Images:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Display Workflow Details
        run: |
          echo "The job was automatically triggered by a ${{ github.event_name }} event."
          echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "The name of your branch is ${{ github.event.workflow_run.head_branch }} and your repository is ${{ github.repository }}."

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ secrets.ACR_TEST_NAME }}
          username: ${{ secrets.ACR_TEST_LOGIN }}
          password: ${{ secrets.ACR_TEST_PASSWORD }}

      - name: Build and push Analytics-Api Docker Image
        uses: docker/build-push-action@v5.0.0
        with:
          file: ./be/src/Project/Services/Analytics/Analytics.Api/Dockerfile
          context: ./be/src
          push: true
          tags: ${{ secrets.ACR_TEST_NAME }}/analytics-api:latest, ${{ secrets.ACR_TEST_NAME }}/analytics-api:${{ github.run_number }}

      - name: Checkout GitOps Repo
        uses: actions/checkout@v2
        with:
          repository: "Team-Eltap/giuru-gitops"
          token: ${{ secrets.GIT_REPOSITORY_TOKEN }}

      - name: Install yq (YAML Processor)
        run: sudo snap install yq

      - name: Update the image tag in Analytics-Api Container deployment.yaml
        run: |
          yq eval '(.spec.template.spec.containers[] | select(.name == "analytics-api-container").image) = "${{ secrets.ACR_TEST_NAME }}/analytics-api:${{ github.run_number }}"' apps/analytics/overlays/test/deployment.yaml -i

      - name: Commit and Push changes
        run: |
          git config --global user.name 'Test Deployment'
          git config --global user.email 'test@deployment.com'
          git add apps/analytics/overlays/test/deployment.yaml
          git commit -m "Updated image tag to ${{ github.run_number }} for Analytics-Api service"
          git push
