apiVersion: v1
kind: Secret
metadata:
  name: b2b-seller-web-secrets
type: Opaque
data:
  RedisUrl: {{ .Values.redisUrl | b64enc | quote }}
  LogzIoToken: {{ .Values.logzIoToken | b64enc | quote }}
  ClientId: {{ .Values.sellerWeb.clientId | b64enc | quote }}
  ClientSecret: {{ .Values.sellerWeb.clientSecret | b64enc | quote }}