apiVersion: v1
kind: Service
metadata:
  name: seller-web-service
spec:
  type: ClusterIP
  selector:
    app: seller-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: seller-web-react-ssr-service
spec:
  type: ClusterIP
  selector:
    app: seller-web-react-ssr
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000